

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPSCommunicationServer.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class gpsEntities : DbContext
{
    public gpsEntities()
        : base("name=gpsEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<devices> devices { get; set; }

    public virtual DbSet<positions> positions { get; set; }

    public virtual DbSet<passenger_counters> passenger_counters { get; set; }

}

}

