
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GPSCommunicationServer.Model
{

using System;
    using System.Collections.Generic;
    
public partial class positions
{

    public int id { get; set; }

    public string protocol { get; set; }

    public int deviceid { get; set; }

    public System.DateTime servertime { get; set; }

    public System.DateTime devicetime { get; set; }

    public System.DateTime fixtime { get; set; }

    public bool valid { get; set; }

    public double latitude { get; set; }

    public double longitude { get; set; }

    public double altitude { get; set; }

    public double speed { get; set; }

    public double course { get; set; }

    public string address { get; set; }

    public string attributes { get; set; }

    public double accuracy { get; set; }

    public string network { get; set; }



    public virtual devices devices { get; set; }

}

}
